[package]
name = "liquid-rust-mir"
version = "0.1.0"
authors = ["Christian Poveda <git@christianpoveda.xyz>"]
edition = "2018"

[dependencies]
liquid-rust-common = { path = "../liquid-rust-common" }
liquid-rust-ty = { path = "../liquid-rust-ty" }

rustc-workspace-hack = "1.0.0"
