[workspace]

members = [
    "liquid-rust",
    "liquid-rust-common",
    "liquid-rust-driver",
    "liquid-rust-fixpoint",
    "liquid-rust-mir",
    "liquid-rust-parser",
    "liquid-rust-ty",
    "liquid-rust-tycheck",
]
