[workspace]
members = [
  "liquid-rust",
  "liquid-rust-common",
  "liquid-rust-core",
  "liquid-rust-core-cli",
  "liquid-rust-driver",
  "liquid-rust-fixpoint",
  "liquid-rust-parser",
  "liquid-rust-typeck",
]

[profile.dev]
debug = false
