[package]
name = "liquid-rust-driver"
version = "0.1.0"
authors = ["Christian Poveda <git@christianpoveda.xyz>"]
edition = "2018"

[dependencies]
rustc-workspace-hack = "1.0.0"
env_logger = "0.8"

liquid-rust-lang = { path = "../liquid-rust-lang" }
liquid-rust-parser = { path = "../liquid-rust-parser" }
