[package]
name = "liquid-rust-driver"
version = "0.1.0"
authors = ["Christian Poveda <git@christianpoveda.xyz>"]
edition = "2018"

[dependencies]
liquid-rust-parser = { path = "../liquid-rust-parser" }
liquid-rust-common = { path = "../liquid-rust-common" }
liquid-rust-tycheck = { path = "../liquid-rust-tycheck" }

rustc-workspace-hack = "1.0.0"
env_logger = "0.8"
