[package]
name = "liquid-rust-parser"
version = "0.1.0"
authors = ["Christian Poveda <git@christianpoveda.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
lalrpop = "0.19.0"

[dependencies]
liquid-rust-common = { path = "../liquid-rust-common" }
liquid-rust-mir = { path = "../liquid-rust-mir" }

lalrpop-util = "0.19.0"
logos = "0.11.4"
